[alias]
ci-test = "nextest run --all-features --locked"
ci-lint = "clippy --all-targets --all-features -- -D warnings"
ci-fmt = "fmt --all -- --check"
ci-bench = "bench --quiet --all-features"
t = "nextest run --all-features"
